---
- hosts: all
  become: true
  tasks:
   - name: Create User Using Ansible
     user:
      name: bahubali
      password: "{{ 'bahubali' | password_hash('sha512') }}"
      state: present
      comment: User created by Ansible
