---
- hosts: ubuntu
  become: true
  tasks:
  - name: Install packages using yum
    yum:
     name: vsftpd
     state: latest
    when: ansible_distribution == "RedHat"
  - name: Install Packages on Ubuntu/Debian servers
    apt:
     name: vsftpd
     state: latest
    when: ansible_distribution == "Ubuntu"
